spring.application.name=spring-boot-security-oauth2

#Github login
spring.security.oauth2.client.registration.github.client-id=Ov23liPx3SeDOcwJKbn2
spring.security.oauth2.client.registration.github.client-secret=22ef77941a65615c40fcf42b5b5d47e94719c6fe

#Google login
spring.security.oauth2.client.registration.google.client-id=1030470896146-1j8ff305ri9o8bl63bhhp9o2p6q4leh1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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


# logging
logging.level.org.springframework.security=Trace
